### ISSUE TITLE
Telnet cedentials G3 FW 3.3.4

### ISSUE THREAD

**Issue by Pitti3301** [sdavides/AqaraG3-armv7-binary#1]
No problem, just a question. After downgrading to 3.3.4, the aQRootG3 hack no longer works for many people. In this situation, the Telnet service can be activated using the click variant 5-2-2-2-2-2. I can also connect to the G3's open WiFi and open telnet. But I can't get any further here, as all password variants have been rejected so far. Is there a solution for this?

**Comment by Wh1terat** [comment]
Bit out of the loop - not sure why no success after downgrading with aQRootG3 ?

But looking at the "click" method, I'm assuming this puts the device into factory mode?

In factory mode the root password is derived from the last 16 chars of:
```base64(hmac_sha256(key, sha256(did+mac+key)))```

```
[persist.sys.miio_mac]: [54:EF:44:31:XX:XX]
[persist.sys.miio_key]: [OEh3QRgJXXXXXXXX]
[persist.sys.miio_did]: [46327XXXX]
```

Honestly, not sure how you'll get the numeric did and key without existing access.
They're not (as far as I can see) returned by any Aqara API endpoint either.

**Comment by sdavides** [comment]
I don't remember how I did it, did you generate the QR code correctly? do the password and sid have special characters? does it tell you "connection error" and then you wait to re-enter the correct data to connect and log in to telnet without restarting the aqara pairing process?

**Comment by sdavides** [comment]
if I remember correctly, I changed the second line of the payload 
'"fw_man"ager.sh -t -f',
'fw_manager.sh -t -f',

**Comment by Wh1terat** [comment]
> if I remember correctly, I changed the second line of the payload '"fw_man"ager.sh -t -f', 'fw_manager.sh -t -f',

That wasn't a typo. It's deliberate. fw_manager.sh is already running and checks the process list for "fw_manager.sh"
The " breaks this up.

**Comment by sdavides** [comment]
aaah ok, I also had problems and played with the script, but I don't remember

**Comment by Pitti3301** [comment]
> I don't remember how I did it, did you generate the QR code correctly? do the password and sid have special characters? does it tell you "connection error" and then you wait to re-enter the correct data to connect and log in to telnet without restarting the aqara pairing process?

the QR code should be correctly generated, the password has special characters and it doesn't tell anything

**Comment by sdavides** [comment]
the wifi password must NOT have special characters, it must NOT contain "/ & $ @ - etc".

the problem could also be the size of the image, try from the PC display and change the zoom while scanning, the voice should say "error.." and rescan with the aqara qr, I remember that I used "./aQRootG3.py Davide davidedavide"
my wifi "Davide" and password "davidedavide", but I don't remember if I played with the payload inside aQRootG3.py
