### ISSUE TITLE
Error running all ptz_*.sh scripts

### ISSUE THREAD

**Issue by Pitti3301** [sdavides/AqaraG3-armv7-binary#2]
Scripts like ptz_up.sh cannot find the mi_motor program. The /data/bin directory is not present on my G3

**Comment by sdavides** [comment]
are you sure?

```

/data/bin # ls -lrt
total 20
-rwxr-xr-x    1 root     root         17320 May  7  2024 mi_motor
/data/bin # pwd
/data/bin
/data/bin # uname -a
Linux Camera-Hub-G3-120C 4.9.84 #41 SMP PREEMPT Wed Oct 16 16:40:45 CST 2024 armv7l GNU/Linux

```

**Comment by Pitti3301** [comment]
ssh root@192.168.120.14
root@192.168.120.14's password: 
1 ulimit=256
~ # uname -a
Linux Camera-Hub-G3-6EA3 4.9.84 #41 SMP PREEMPT Wed Oct 16 16:40:45 CST 2024 armv7l GNU/Linux
~ # cd /data
/data # ls -lrt
total 4
drwxr-xr-x    4 root     root           496 Jan  1  1970 storage
drwxr-xr-x    2 root     root           520 Jan  1  1970 ha_driven
-rw-rw-rw-    1 root     root            94 Jan  1  1970 gatewayInfoJson.info
drwxr-xr-x    2 root     root           304 Jan  1  1970 ai
drwxr-xr--    2 root     root           160 Jan  1  1970 dfu
drwxr-xr-x    2 root     root           240 Jan  1  1970 utils
drwxr-xr-x    2 root     root           232 Jan  1  1970 scripts
drwxr-xr-x    2 root     root           232 Dec  8 05:53 ota_dir
drwxr-xr-x    2 root     root           160 Dec  9 03:30 ota-files
drw-------    2 root     root           696 Dec  9 03:32 zigbee
/data #

**Comment by sdavides** [comment]
download mi_motor file from my repo

**Comment by Pitti3301** [comment]
Thank you very much, now ptz works. What files should still be in /data/bin? Can you actually turn off the cloud services completely? The camera should only work in my LAN. After each restart of the camera, the root password is deleted again and I have to enter it again. Can this be set permanently?Am 10.12.2024 um 11:28 schrieb sdavides ***@***.***>:﻿
download mi_motor file from my repo

**Comment by sdavides** [comment]
/data/bin I created it and there is only that file.

The password is deleted at every start in the post_init.sh "passwd -d $USER" or "passwd -d root".
is necessary for first access, otherwise the default one that you don't know is set
you can add on post_init.sh 
`echo "root:password" | chpasswd 2>/dev/null #set pass root password`

For the cloud, do you have the option to block internet on a device/IP in your modem?

**Comment by Pitti3301** [comment]
I have adjusted the file sshd_start.sh to my password. Thanks for the tip.
In the router I can block traffic to the Internet for the camera. Personally I would prefer a firmware mod. Unfortunately I don't have the knowledge for that.
Do you know why the user and password of the RTSP stream change with every reboot? Is it possible to set this permanently?

**Comment by sdavides** [comment]
rtsp daemon is started with "rtsp -a" which sets username and password, it is started and restarted by other processes like ha_basis, app_monitor.sh which cannot be modified.

You can restart it with `killall -9 rtsp && rtsp >/dev/null 2>&1 &` as written in my guide.
reading the help I guess you can set a username and password "-u -p"

Usage: rtsp
  Arguments:
    -h --help                   print this help
    -d --debug                  debug mode
    -u --username <name>        set username if authentication enabled(default is random)
    -p --password <password>    set password if authentication enabled(default is random)
    -P --port <port>            listen port, default is : 8554
    -d --debug                  debug mode
    -a --auth                   need auth
    -i --ip <listen ip>         bind address

blocking the internet is the fastest and most reliable solution, and you can reactivate it with one click.
